//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDichVu
    {
        public int MaDV { get; set; }
        public int SoLuong { get; set; }
        public System.DateTime NgaySD { get; set; }
        public int MaBookRoom { get; set; }
    
        public virtual BookRoom BookRoom { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
