//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichDonPhong
    {
        public int MaBookRoom { get; set; }
        public int MaNV { get; set; }
        public System.DateTime NgayLam { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public int MaLich { get; set; }
    
        public virtual BookRoom BookRoom { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
