//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int SoLuong { get; set; }
        public bool TrangThai { get; set; }
        public int MaBookRoom { get; set; }
        public int MaMonAn { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual BookRoom BookRoom { get; set; }
        public virtual TTMonAn TTMonAn { get; set; }
    }
}
