//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.LichDonPhongs = new HashSet<LichDonPhong>();
            this.PhanQuyens = new HashSet<PhanQuyen>();
        }
    
        public int MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> SDT { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayBDL { get; set; }
        public string Password { get; set; }
        public Nullable<double> Luong { get; set; }
        public Nullable<int> MaCV { get; set; }
        public Nullable<int> MaPhongBan { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichDonPhong> LichDonPhongs { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanQuyen> PhanQuyens { get; set; }
    }
}
