//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public string MaTaiKhoan { get; set; }
        public Nullable<bool> TrangChu { get; set; }
        public Nullable<bool> TiepNhanKhach { get; set; }
        public Nullable<bool> DanhSachPhong { get; set; }
        public Nullable<bool> LoaiPhong { get; set; }
        public Nullable<bool> DichVu { get; set; }
        public Nullable<bool> ThucDon { get; set; }
        public Nullable<bool> PhongBan { get; set; }
        public Nullable<bool> KhuVuc { get; set; }
        public Nullable<bool> ThongTinKhach { get; set; }
        public Nullable<bool> ThongTinNV { get; set; }
        public Nullable<bool> DanhSachHD { get; set; }
        public Nullable<bool> ChucVu { get; set; }
        public Nullable<bool> LichDonPhong { get; set; }
        public Nullable<bool> TKCuaTui { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<bool> PhanQuyen1 { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
