//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatDung
    {
        public int MaVD { get; set; }
        public int MaPhong { get; set; }
        public string KichThuoc { get; set; }
        public bool TTWiFi { get; set; }
        public string SLGiuong { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
