//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vv_Phong
    {
        public int MaPhong { get; set; }
        public string TenPhong { get; set; }
        public double GiaPhong { get; set; }
        public int MaLoaiPhong { get; set; }
    }
}
