//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vv_PhongHD
    {
        public int MaPhong { get; set; }
        public string TenPhong { get; set; }
        public int MaLoaiPhong { get; set; }
        public string MoTa { get; set; }
        public string ViTri { get; set; }
        public int TrangThai { get; set; }
        public int NguoiLon { get; set; }
        public int TreEm { get; set; }
        public Nullable<int> MaKV { get; set; }
        public byte[] Anh { get; set; }
    }
}
