//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vv_rpNhanVien
    {
        public string TenNV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string gioitinh { get; set; }
        public Nullable<int> SDT { get; set; }
        public string TenPhongBan { get; set; }
        public string TenCV { get; set; }
        public Nullable<System.DateTime> NgayLam { get; set; }
        public Nullable<int> MaCV { get; set; }
        public int MaPhongBan { get; set; }
        public int MaNV { get; set; }
        public string Email { get; set; }
        public string TrangThai { get; set; }
    }
}
